### ISSUE TITLE
add support for the Stardict format as output format

### ISSUE THREAD

**Issue by humenda** [freedict/fd-dictionaries#11]
Stardict is a widely used format and is hence worth supporting. There's also a
mobile client QDict available which understands this format. Since we don't have a client, it'd be great to make our dictionaries available this way.

**Comment by bansp** [comment]
Not a bad idea. Have they published their schema and documentation?
I recall investigating one such case across user forums, with zero effect. But I can't recall now if it was StarDict or some other platform. :-)

**Comment by humenda** [comment]
Is the stardict not the same across the platforms? I won't be able to have a
look ATM, but I'm sure that it's possible to figure out how this format works.
There are enough open source implementations available.
-- 
Web: http://www.crustulus.de (English|Deutsch)  | Blog: http://www.crustulus.de/blog
FreeDict: Free multilingual dictionaries - http://www.freedict.org
Freies Latein-Deutsch-Wörterbuch: http://www.crustulus.de/freedict.de.html

**Comment by humenda** [comment]
The XDXF project seems to have an easy method to support Stardict with the dictd format as intermediate:

"to convert from dictd format to stardict: makedict -o stardict file.index"

**Comment by bansp** [comment]
Let's fork it, then, if it's forkable. I can imagine that it may need tweaking on both sides.

**Comment by humenda** [comment]
I wouldn't fork it, rather work with them, wherever possible. I'll talk to them at some point.

**Comment by bansp** [comment]
I meant being able to adjust the code to match our potential modifications, and then pushing into their master. And well, yes, publishing from our own repo, just to make sure that these changes are in. But it's just thinking aloud.

**Comment by karlb** [comment]
Moved to https://github.com/freedict/tools/issues/5.
