### ISSUE TITLE
Add support for the DictionaryForMID format

### ISSUE THREAD

**Issue by humenda** [freedict/fd-dictionaries#13]
DictionaryForMID is a dictionary program featuring a custom format, importer
scripts and also an Android client.
Documentation seems good and both authors of the desktop / mobile version are
active. Their architecture model is described here:
<http://dictionarymid.sourceforge.net/development.html>.

For the short term, we could easily leverage their dictd2dictionaryformid
conversion process, see
<http://dictionarymid.sourceforge.net/DfM-Creator/index.html> and the GUI
<http://dictionarymid.sourceforge.net/DfM-Creator/gui-DictdToDictionaryForMIDs.html>.

For the longer term, I'd like to create template overrides for our style sheets
which would format certain parts of our format differently, so that we could
make use of the formatting features of the DictionaryForMID format. For
instance, example sentences can be formatted separately. That is ideally not to
much effort, since the format in use is quite close to the dictd format, see
<http://dictionarymid.sourceforge.net/faq.html>.

Last but not least, the project features its own API to inform about new
dictionaries and more importantly, to push the dictionaries to mobile devices.
See <http://dictionarymid.sourceforge.net/ota.php?p=1>.

I would like to see this format supported and would love to integrate our
FreeDict API into DictionaryForMID, so that we don't replicate efforts.

**Comment by bansp** [comment]
I looked at the linked pages (and a few more) and can't find those extra codes, could you please link them? 
Maybe inserting these codes could be a matter of an option in how the tei2dict stylesheet is invoked.

**Comment by tunichtviel** [comment]
In the DictionaryForMIDs terminology we use "Content Declarations" to denote pronunciations, articles, explanations, or whatever content is used by a dictionary.

Each 'content' is marked by content tags (example):
`dictionary [01dikshionari] [02noun] [03A book that contains translations for words.]`

Further explained at http://dictionarymid.sourceforge.net/DfM-Creator/newdictContent.html

And, of course, if there are any questions, please ask!

**Comment by tunichtviel** [comment]
Besides: those freedict dictionaries that I converted to DictionaryForMIDs format (that was > 5 years ago!) already use that Content Declaration to tag the pronunciation.

**Comment by karlb** [comment]
Moved to https://github.com/freedict/tools/issues/6.
