### ISSUE TITLE
hun-eng/eng-hun: remove binary blob

### ISSUE THREAD

**Issue by humenda** [freedict/fd-dictionaries#17]
We currently ship eng-hun and hun-eng in a binary file. Upstream is not active anymore and hence it would be better to maintain a fork in TEI, so that the dictionary is open for improvements.

**Comment by rickysarraf** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

On Tue, 2017-02-14 at 02:04 -0800, Sebastian Humenda wrote:
> We currently ship eng-hun and hun-eng in a binary file. Upstream is not active
> anymore and hence it would be better to maintain a fork in TEI, so that the
> dictionary is open for improvements.

Yes. I agree with this. Even if they get active in the future, we could
collaborate back with them.


- -- 
Ritesh Raj Sarraf
RESEARCHUT - http://www.researchut.com
"Necessity is the mother of invention."
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCgAdFiEEQCVDstmIVAB/Yn02pjpYo/LhdWkFAlii6xsACgkQpjpYo/Lh
dWly1hAAqmMRsZBJnIrFosc31yKmwOHEXuZa3SSs/mvowBcxjTeTAWnKYXKIgabB
cfzz/2s+mFJZDQbea+6rgY2JIeDMiqVUOwKZOrXIw7b/CFIG4JX2qOwgCARhxB/U
NFdTb0a0LwtMcICU5qnMvHXCFRTaIihG7dj1VW96Kf7/f2UNsACEVMNVMUqirgdd
/dnujOFoOqETSXfmvulBpVGk8UakRi5QPDCNPK9Q2pUKfzACPv9zP7TevswjZ6yp
wQVAc0b12CBB0gglDf5CsrVFEAKNQnc268oQgZ1uH4ihlF+cljLNDfj98DiGFWCo
GKrxbC4eK59j85LvmRFauVcQQgF78MF8QKxWBPtSJTo29Y+5g/6MluuDtdmyy9Uu
5oo1DZJ8t2uFwdTxKvThOS29DyqbUYtKfc6Vf7304ok612/qwl3ce15TBJURKicP
qRxYXNEDMpwHa4YEzo0nRW5ozWfWu1a61ibATF5Ff/u/RmyRVk0foCITaHAiysd1
EKWBYlCfq6TjnsCtUNKB74FFfaUSbfDpn4Erufgsr9Mg1JqY2f6qqAyjAtOSHdch
276nF23HpUwnq3DVYnPqjcJlt/lyEKnSRa2LMez2QRmD26AjS8Gy0pkl0Ti/QiMD
jZrY23Zw75okPoSRcQeOsh1pd6a3NG0nubmc6QapZX5m1IFmkz4=
=5WSF
-----END PGP SIGNATURE-----
