### ISSUE TITLE
Don't use bash-specific scripting in the Makefile

### ISSUE THREAD

**Issue by humenda** [freedict/fd-dictionaries#18]
In one of the Makefiles, SHELL=bash is set. It's questionable whether depending on a particular shell, especially from a Makefile, is a good idea.

**Comment by lwm** [comment]
> whether depending on a particular shell

But it's the most likely shell? On which *NIX-like system is bash not installed?

Just passing by and saw this, I'm no Makefile expert either ;)

**Comment by humenda** [comment]
>> whether depending on a particular shell
>
>But it's the most likely shell? On which *NIX-like system is bash not installed?
Debian's default shell is dash, for performance reasons, I believe. I am not
sure whether a minimal system would install bash, these days.

On my Debian 9.0 machine, actually only three of the installed packages depend
on bash.

I don't have anything against Bash, I personally would just like to avoid
depending on one particular shell. I'm open for objections.

**Comment by lwm** [comment]
> Debian's default shell is dash, for performance reasons, I believe.

Ah, I did not know. Seems like you are on the right track then :+1:

**Comment by joostvb-gh** [comment]
On Thu, Mar 16, 2017 at 08:26:07AM -0700, Sebastian Humenda wrote:
> >> whether depending on a particular shell
> >
> >But it's the most likely shell? On which *NIX-like system is bash not
> >installed?
>
> Debian's default shell is dash, for performance reasons, I believe. I am not
> sure whether a minimal system would install bash, these days.

Debian's default /bin/sh is dash, indeed.  The default user login shell is
bash.  I believe indeed if you try hard you could create a minimal Debian
system without bash.

> On my Debian 9.0 machine, actually only three of the installed packages depend
> on bash.
> 
> I don't have anything against Bash, I personally would just like to avoid
> depending on one particular shell. I'm open for objections.

It's "nice to have", to be able to build and run freedict with any
bourne-compatible shell.  However, if in some Makefile specific bash-features
are needed and used, I feel depending upon bash is not a big deal.  Only if one
has too much time on one's hands, one could work on reimplemting the needed
functionality in pure bourne shell code.  Explicitly specifying SHELL=/bin/bash
would yield just one extra package in the list of build-time dependencies.

Just a remark here, not an objection :)

Bye,

Joost

-- 
irc:joostvb@{OFTC,freenode} ∙ http://mdcc.cx/ ∙ http://ad1810.com/

**Comment by humenda** [comment]
I was reconsidering this issue. I think the remarks on "most of the systems have bash" are actually true. I would rather Since this is very low priority at the moment, I close this issue. For new code in makefiles, I do want to see POSIX and non-bash-specific code and if anybody has the time to work on tis rather simple issue, please feel free to submit a PR.
Thanks
