### ISSUE TITLE
Project Description

### ISSUE THREAD

**Issue by bendman** [freedict/fd-dictionaries#2]
Is this the new home of the project? If so, where can I find info on the project, for example:
- [ ] Project goals
- [ ] Dictionary format
- [ ] Dictionary reading/writing tools
- [ ] Installation instructions
- [ ] Usage
- [ ] History

I'm not sure if all of these points apply or would be useful, but at least some form of README and project description would be useful and help potential contributor. If I can find any of this myself (or be pointed in the right direction) then I can get some form of description started.

**Comment by humenda** [comment]
Hello Ben,

Ben Duncan schrieb am 04.12.2015,  9:46 -0800:
>Is this the new home of the project? If so, where can I find info on the project,
Yes, it is. Please have a look on http://freedict.org for the "proper" project
project page.

>For example:
>- [ ] Project goals
>- [ ] Dictionary format
[...]
If any of these are not addressed  on the mentioned page, please feel free to
report that so that we can fix it.

Cheers
Sebastian
-- 
Web: http://www.crustulus.de (English|Deutsch)  | Blog: http://www.crustulus.de/blog
FreeDict: Free multilingual dictionaries - http://www.freedict.org
Freies Latein-Deutsch-Wörterbuch: http://www.crustulus.de/freedict.de.html

**Comment by bansp** [comment]
They might have vanished together with (re)vanishing of the wiki, 
unfortunately. I think we should try to move or import the contents of 
the wiki to GitHub, somehow.

Best,

   Piotr

**Comment by bendman** [comment]
Thanks @humenda, that page is helpful, and I see now that it is actually contained in this repo.  Maybe it would help to link from the repo to that page (in the repo description at the top, or in a README in the home directory), and to link from that page to the Github repo rather than SourceForge, if this is the new home of the source.

**Comment by humenda** [comment]
Hi there

Ben Duncan schrieb am 04.12.2015, 13:19 -0800:
>Thanks @humenda, that page is helpful, and I see now that it is actually
>contained in this repo.  Maybe it would help to link from the repo to that page
>(in the repo description at the top, or in a README in the home directory), and
[...]
After your previous message I've actually added the missing README file. Yes, a
link in the project description would be helpful.

Please keep in mind that migration to GitHub is still work in progress, so
freedict.org needs changing. Thanks for making us aware.

Cheers
Sebastian

**Comment by bendman** [comment]
No worries! Don't consider it a complaint so much as an attempt to get it documented in the public domain to help attract Pull Requests.

Thanks for the great resource.
