### ISSUE TITLE
Adding words

### ISSUE THREAD

**Issue by lwm** [freedict/fd-dictionaries#20]
Hi there, great to see this repository and initiative! 

I was hoping to build a CLI tool which would benefit from such translations. However, rather than just take translations, I'd also hope to add them upstream when they are missing. 

I saw the following commit https://github.com/freedict/fd-dictionaries/commit/0f1aa58492f0b7e62aa1993c13260f73075a3f99 and was wondering what do I need to do to submit a pull request with new words? Just add the words and bump the version?

Do you have existing command line tool which can manipulate (add words to) the XML? (EDIT: Oh, I saw in [this wiki page](https://github.com/freedict/fd-dictionaries/wiki/FreeDict-HOWTO-%E2%80%93-XML-Markup) you are working on it!?)

Thanks!

**Comment by humenda** [comment]
Hi

>I was hoping to build a CLI tool which would benefit from such translations.
>However, rather than just take translations, I'd also hope to add them upstream
>when they are missing.
The best place to discuss such issues is our mailing list FreeDict beta, still
at SourceForge, you can also join `#freedict` in the OFTC (IRC) network.
What do you mean by upstream? In some cases, we are upstream. Take the
Latin-German dictionary. That is hand-crafted and FreeDict is upstream. For
other dictionaries, e.g. eng-deu, upstream is somebody else. For errors there,
we try to notify upstream, let them fix the issue and import the data again.

>I saw the following commit
>https://github.com/freedict/fd-dictionaries/commit/0f1aa58492f0b7e62aa1993c13260f73075a3f99
>and was wondering what do I need to do to submit a pull request with new words?
>Just add the words and bump the version?
That's a clear yesno.
Short answer: if you want to contribute: please introduce yourself on the
mailing list and we make you a contributor. That makes things far easier.

As for the pull requests:
For some dictionaries, we do have maintainers, which are denoted in the XML
header of the TEI files. For a lot of others, it depends. Fixes are welcome,
really, but we probably would need to modify the pull request. Despite the
version number, the change log, author information and headword count have to be
correct. We would like to avoid patching sources which we import from upstream.
For a lot of cases, this is not problematic. Just make sure you have a look at
the TEI header once and we take care of applying these changes, once you have
made a pull request.

>Do you have existing command line tool which can manipulate the XML?
Sadly no. It's fairly easy to transform word lists into TEI XML and if you could
tell us what your skills are and what you are most comfortable to use, we
certainly find a solution.

You could for instance write your words in the Ding format, for which we plan to
write a importer in the near future.

Most of that is discussed in the Wiki, please have a look there too: https://github.com/freedict/fd-dictionaries/wiki

Thanks

**Comment by lwm** [comment]
> What do you mean by upstream? In some cases, we are upstream.

Ah yes, I meant you. But I also get your point that some times upstream is someone else.

> please introduce yourself on the mailing list

Will do!

> Fixes are welcome, really, but we probably would need to modify the pull request. Despite the version number, the change log, author information and headword count have to be correct. We would like to avoid patching sources which we import from upstream.

Ah, I see.

>> Do you have existing command line tool which can manipulate the XML?
> Sadly no. It's fairly easy to transform word lists into TEI XML and if you could
> tell us what your skills are and what you are most comfortable to use, we
> certainly find a solution.
> 
> You could for instance write your words in the Ding format, for which we plan to
> write a importer in the near future.

I write Python mostly. I'll keep an eye on the mailing list and see if I can help!

I'll check the wiki pages then, thanks! :+1:

**Comment by humenda** [comment]
>> What do you mean by upstream? In some cases, we are upstream.
>
>Ah yes, I meant you. But I also get your point that some times upstream is someone else.
Right, I wasn't sure.

>>> Do you have existing command line tool which can manipulate the XML?
>> Sadly no. It's fairly easy to transform word lists into TEI XML and if you could
>> tell us what your skills are and what you are most comfortable to use, we
>> certainly find a solution.
>> 
>> You could for instance write your words in the Ding format, for which we plan to
>> write a importer in the near future.
>
>I write Python mostly. I'll keep an eye on the mailing list and see if I can help!
Python is awesome. There's [Pyglossary](https://github.com/ilius/pyglossary). It
only supports TEI as a writer in an pretty ancient version, but updating this
shouldn't be too hard. Once done, you could use tab-delmited word lists or CSV
files. That is something I'd like to look into, maybe you want have a look, too
:).

**Comment by lwm** [comment]
> Python is awesome.

Agreed!

> It only supports TEI as a writer in an pretty ancient version, but updating this shouldn't be too hard. 

I'm kinda new to all this but is there somewhere to see the difference between the TEI versions? I suppose there are specifications? My web search skills are failing me ...

**Comment by bansp** [comment]
Can of worms... there is a generic translator from P4 into P5, but one's best bet in such a case is to look at the intended semantics and to apply it to the format we now use in Freedict. 
Having said that, I need to add that I kind of hope to be able to change this format slightly, once the TEI-Lex0 recommendations are out.
I wouldn't recommend pyglossary modification as a project for now. For December, maybe :-)
