### ISSUE TITLE
Add support for the colloc tag

### ISSUE THREAD

**Issue by humenda** [freedict/fd-dictionaries#22]
At the moment, the [colloc tag](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-colloc.html) is not supported by the style sheets. It seems as if it were already present as an attribute, though.
I could have a look at the weekend at changing the style sheets, but would be happy if a XSL expert would have time for this little task.

Ah yes, justification: dan-eng :)

**Comment by fceschmidt** [comment]
For a short example, the following TEI entry

```xml
         <entry>
            <form>
               <orth>deltage</orth>
            </form>
            <gramGrp>
                <pos>v</pos>
                <colloc>i</colloc>
            </gramGrp>
            <sense>
               <cit type="trans">
                  <quote>participate</quote>
                  <gramGrp>
                      <pos>v</pos>
                      <colloc>in</colloc>
                  </gramGrp>
               </cit>
               <cit type="trans">
                  <quote>take part</quote>
                  <gramGrp>
                      <pos>v</pos>
                      <colloc>in</colloc>
                  </gramGrp>
               </cit>
               <cit type="example">
                   <quote>Vi deltager i konkurrencen.</quote>
                   <cit type="translation">
                       <quote>We take part in the competition.</quote>
                   </cit>
               </cit>
            </sense>
         </entry>
```

generates this DICT entry:

```
deltage <v>
participate <v>, take part <v>
      "Vi deltager i konkurrencen."  - We take part in the competition.
```

If possible, I would prefer to have something like the following instead:

```
deltage (i) <v>
participate (in) <v>, take part (in) <v>
      "Vi deltager i konkurrencen."  - We take part in the competition.
```

By the way I've also thought about using something like `<usg type="gram">participate in sth.</usg>` for this, and frankly I don't know what would be considered more correct.

**Comment by fceschmidt** [comment]
Also I just found out that a `gramGrp` with only ignored element inside, such as:

```
<gramGrp>
    <colloc>in</colloc>
</gramGrp>
```

produces empty angle brackets, like:

```
<>
```

**Comment by humenda** [comment]
Yes, that makes perfectly sense. If there's a `gramGrp` tag, the `[]` are added
to the output. The `colloc` tag is a special case, because it's not supported,

Thanks
so the brackets remain empty.

**Comment by fceschmidt** [comment]
I added a comment to line 122 of the commit 7dcdbaf. It's just about the selector in the `xsl:value-of` clause, which I found to be quite easy to fix, so please consider correcting this. I appreciate your dedication!
