### ISSUE TITLE
eng-hun: check for missing spaces

### ISSUE THREAD

**Issue by humenda** [freedict/fd-dictionaries#24]
I'm lacking knowledge in Hungarian, but some of the words seem too long. It
should be checked whether these terms lack spaces. Breaking up some of them
give results at Google, the long forms don't.

**Comment by bansp** [comment]
I was sure this got posted as a bug back in SF times, but all I can find there is this:
https://sourceforge.net/p/freedict/bugs/8/

**Comment by bansp** [comment]
Ah, here we go -- it was posted as a feature request: https://sourceforge.net/p/freedict/feature-requests/1/

**Comment by humenda** [comment]
Well, I thought that issue got resolved already :-(. I would feel much more
comfortable if I could find somebody who actually speaks (some) Hungarian.
I will try to have a look at the Perl importer script, maybe I'm able to figure
out what is going wrong.

**Comment by humenda** [comment]
My mistake, spaces are there.
