### ISSUE TITLE
Update german-english dictionary

### ISSUE THREAD

**Issue by jonathan-s** [freedict/fd-dictionaries#44]
The following dictionary is open source and has fairly good meta data. 
https://www-user.tu-chemnitz.de/~fri/ding/

You can download the text dictionary here:
https://ftp.tu-chemnitz.de/pub/Local/urz/ding/de-en/

It would be great if the german dictionary could put this to use!

**Comment by humenda** [comment]
Hi

>The following dictionary is open source and has fairly good meta data. 
We already use this dictionary, though in a very old revision. 
There's also a draft of a new importer script / program on branch
`extend_ding2tei_grammar_parsing_capabilities`. Would you have time to look into
this? The architecture isn't ideal yet.

Thanks

**Comment by jonathan-s** [comment]
I can only see the master branch.

**Comment by micha137** [comment]
It is a branch in the [tools repository](https://github.com/freedict/tools): https://github.com/freedict/tools/tree/extend_ding2tei_grammar_parsing_capabilities

**Comment by jonathan-s** [comment]
@humenda So far what I've done is that I downloaded the dictionary form dict.cc and turned that into a more usable format for myself. It'd be possible to adapt that script to more towards the format that freedict uses.

**Comment by humenda** [comment]
Is this under a free license? If so, it might be a good addition (or
replacement) for what we currently have.

What format is "usable" for you? We export to Slob these days, which seems the
most feature-rich and maintained dictionary format these days.

**Comment by jonathan-s** [comment]
It's worth noting that the dictionary at dict.cc is based on the dictionary from here: https://dict.tu-chemnitz.de/doc/faq.en.html which is under GPL license, since GPL is a copyleft, the dictionary that you're able to to download at dict.cc should fall under the same terms.

**Comment by humenda** [comment]
Now that you're mentioning it, I remember having investigated this as well.
We're trying to import the original ATM. I wonder whether staying with the
original or the fork is better. I'll sort this out as soon as time permits.
Unless somebody else steps up :).

**Comment by humenda** [comment]
We have addressed this with a new importer from Einhard Leichtfuss, so we're shipping the up-to-date version
