### ISSUE TITLE
Consider alternative phonetic transcription tools (if/when needed)

### ISSUE THREAD

**Issue by bansp** [freedict/fd-dictionaries#49]
I've just noticed this thread at Corpora-L: "IPA conversion tool" https://mailman.uib.no/public/corpora/2019-April/030032.html 

People mention:
- https://github.com/bootphon/phonemizer
- http://espeak.sourceforge.net/
- https://github.com/dmort27/epitran

So I thought I'd make a note of that here, just in case.

**Comment by humenda** [comment]
Hi

>- http://espeak.sourceforge.net/

Espeak  is dead and espeak-ng is its successor that we already use. It would be
interesting to see a proper comparison from the other tools that you mention
against espeak-ng from somebody who can read IPA (I cannot). The huge advantage
with espeak-ng is that it is used by thousands of blind people around the world
for their daily work, so that it has a large user base reporting pronunciation
errors.

**Comment by humenda** [comment]
Hi

Thanks for bringing this up.

>- https://github.com/bootphon/phonemizer
This is just a wrapper around espeak/espeak-ng, see below.

>- http://espeak.sourceforge.net/
As Espeak is unmaintained for a while and Espeak-ng is its successor, we decided
to use this for the IPA conversion. Michael's script does all the XML and
Espeak-processing work, so using your first option would only add another
abstraction layer without any benefit. From our perspective, 1) and 2) are
equivalent.

>- https://github.com/dmort27/epitran
I am not sure about this. Its wording suggests that people with a more
lexicographic background are involved. However, I bet that Espeak supports more
languages and given that it's pronunciation is very accurate and its used for
everyday-use in many [screen
readers](https://en.wikipedia.org/wiki/Screen_reader), I am convinced that it is
the superior tool. More contributors, more users, more corrections.
I would vote to close this issue, if you do not have any objections.

**Comment by bansp** [comment]
Thanks for looking at the issue, Sebastian -- I only meant to share a couple of links that came up in a mailing list conversation as recommendations. No problem about closing this ticket.
