### ISSUE TITLE
Implications of GPL as a license for dictionaries

### ISSUE THREAD

**Issue by sildar** [freedict/fd-dictionaries#58]
Hi,

At least some of the dictionaries are licensed under GPL, a free non-permissive license initially created for software but [that can also be used for art/text](https://www.gnu.org/licenses/gpl-faq.en.html#GPLOtherThanSoftware) (even if not always encouraged by GNU). Any derivative work has to be licensed under GPL, as stated in the license:

> You may convey a work based on the Program [...] provided that you also meet all of these conditions:
> 
> c) You must license the entire work, as a whole, under this License to anyone who comes into possession of a copy. **This License will therefore apply [...] to the whole of the work, and all its parts, regardless of how they are packaged. This License gives no permission to license the work in any other way**, but it does not invalidate such permission if you have separately received it.

I understand that one of its implications is that any distributed improvement (fixing translations, adding some) shall be distributed under GPL, but it is less clear to me how this interacts with non-free software using the dictionaries as data to perform some task (eg, spelling checker, automated translation, word generator, ...). I couldn't find any related information in the GitHub Wiki or on the website.

[The closest entry in the GNU GPL FAQ would be related to plugins](https://www.gnu.org/licenses/gpl-faq.en.html#NFUseGPLPlugins) and states:

> Can I release a nonfree program that's designed to load a GPL-covered plug-in?

>  If they form a single combined program then the main program must be released under the GPL or a GPL-compatible free software license, and the terms of the GPL must be followed when the main program is distributed for use with these plug-ins.
> However, if they are separate works then the license of the plug-in makes no requirements about the main program.

While open to interpretation, my guess is that GPL would allow the use cases I described earlier (spelling checker, etc..).

[A related question can be found on SE](https://softwareengineering.stackexchange.com/questions/312774/gpl-dictionary-usage-in-commercial-application), but the most upvoted answer has only one upvote, wich makes it unreliable.

[Another SE related question also states that GPL does not apply to programs using datasets under GPL](https://opensource.stackexchange.com/questions/5564/using-gpl-covered-dataset-in-non-gpl-code).

Licenses are a difficult topic and it's easy to get something wrong, do you have any input about what can and cannot be done with the dictionaries, and if there are restrictions attached? I think it would be nice to have a short section about licenses in the documentation so as not to discourage use of this resource.

Thanks for your great work!

**Comment by karlb** [comment]
I consider the GPL an unfortunate choice for dictionaries, but there's no easy way to change the license, unfortunately.

Personally, I have the same interpretation as https://opensource.stackexchange.com/questions/5564/using-gpl-covered-dataset-in-non-gpl-code, but I don't feel confident enough regarding this topic to really give an answer.

> I think it would be nice to have a short section about licenses in the documentation so as not to discourage use of this resource.

I agree.

**Comment by joostvb-gh** [comment]
Hi sildar,

Thanks for your valid question.  I'm afraid I cannot really help though: it looks to me you've done
all research I'd have been able to do, and it seems it is indeed a difficult question.  I guess only
qualified lawyers are capable of shedding some light here.  Or _maybe_ if more details about
what we're exactly talking about here are supplied more tangible conclusions might be reached.
How are the two works being combined exactly?

Bye,

Joost

**Comment by humenda** [comment]
Thank you very much for the research on this. As I am not a lawyer as well, my
understanding with the provided resources is that it is fine for a program to
use GPL datasets, as long as it provides the copyright notice to the user. We
are a data provider and hence cannot enforce this.

If it were the case that non-free programs could make use of GPL data, I would
go even argue that it is the best licence to choose. I know that people have
different opinions on data and software freedom.

For the practical implications it would be interesting where you would like to
see what formulation of licence info. Even though this is mentioned in the
README, this repository **does not** contain all dictionaries and hence putting
an licence info here is incomplete. We could put it on the website, but then
again, where?
As for the text, I would like to see a draft that summarises the current
knowledge that we have about our licence and its applicability from either the
OP or from @karlb or @joostvb-gh.
I could try to get an informal advice about this draft afterwards.

**Comment by sildar** [comment]
@joostvb-gh 
> How are the two works being combined exactly?

My specific use case is not really relevant since I do not plan on distributing my software, it will be used internally at my company, so it seems GPL is even less restrictive to me (it applies only when distributing). I do think however that it would be great to have that kind of info on the website so that people don't have to search for themselves and end up with inconclusive answers or a wrong one.

@humenda 
> We could put it on the website, but then
again, where?

I think the "Documentation" section on the website would be a great place to put it (it's short enough to add stuff) even if one could advocate for the Home Page under the "Use For Any Purpose" section.

> As for the text, I would like to see a draft that summarises the current
knowledge that we have about our licence and its applicability

As none of us are lawyers, we should be very careful with our wording. As an example, my understanding would be that a graphical interface to display only those dictionaries would need to be distributed under GPL while a translation software using these dictionaries would not (see [this GNU FAQ entry](https://www.gnu.org/licenses/gpl-faq.en.html#WhatCaseIsOutputGPL)).

**Comment by humenda** [comment]
My proposal is as follows

```
## Licencing and Reuse

FreeDict provides its dictionaries under free and open source licences that
allow the users to study, modify, extend and redistribute them, given that the
licencing conditions are met. Each dictionary has separate licencing terms
which are located in the TEI header at the beginning of each dictionary file.
We advice you to check this out first or to ask on the mailing list, if
unsure.

The majority of our dictionaries is licenced under GPL. If you plan to make
use of these dictionaries, you should study the licence terms carefully. To
the best of our knowledge, GPL does permit bundling the dictionary in a
commercial product, but requires you to hint the user about the licence of the
data. Furthermore you need to link the sources, including the complete
publication of modifications made. Definite advice can only be given by a
lawyer and we make you hereby aware that we are only representing our
understanding here.
```

**Comment by karlb** [comment]
Looks good to me. I suggest the following tweaks (changes in bold):

> The majority of our dictionaries is licenced under GPL. If you plan to make use of these dictionaries, you should study the licence terms carefully. To the best of our knowledge, GPL does permit bundling the dictionary in a commercial product, but requires you to **inform** the user about the licence of the data. Furthermore you need to link the **dictionary** sources, including **all** modifications made. Definite advice can only be given by a lawyer and we make you hereby aware that we are only representing our understanding here.

**Comment by joostvb-gh** [comment]
It looks good to me.  You _might_ even want to trim it a bit, and just refer to 'consult a lawyer' and 'see the headers for the licence text', to be even more on the safe side.  And karlb's suggestions
make it more clear, too.  HTH :)  Bye, Joost

**Comment by sildar** [comment]
Thanks for coming up with a proposal.

You could also add a reference to this issue since I think some links provided in our discussion might help.

Maybe in this last sentence;

> we are only representing our understanding here.

I have no other suggestion, thanks again for tackling this!

**Comment by humenda** [comment]
Thanks, this is done now.
