### ISSUE TITLE
LFS needed

### ISSUE THREAD

**Issue by vpvn** [freedict/fd-dictionaries#59]
I made a dictionary eng-rus, it's a compilation of wikdict and stardict dictionaries with a lot of manual edits. It counts 526876 headwords cause the stardict dictionary is comprehensive, so the eng-rus.tei file exceeds 160Mb. How I can push it to the repository? It seems that there is no support of LFS in the target repository.

**Comment by karlb** [comment]
With LFS we would lose usable diffs for that file, wouldn't we? Could we maybe treat this as an autogenerated dictionary by storing the generation code and the diffs for the manual changes?

@vpvn , what are your plans for this dictionary? Do you intend to maintain it in the future? If so, will you continue editing manually, or do you plan to reimport updated versions of your source dictionaries?

Are the dictionary licenses compatible?

**Comment by vpvn** [comment]
Yes, you are right, LFS doesn't support diff. Thank you for your questions, I'll think about the best way to implement this dictionary in fd project. About licenses, there is no problem. StarDict is under GNU Public License and WikDict uses Creative Commons Attribution-ShareAlike 3.0 Unported license.

**Comment by humenda** [comment]
@vpvn Please tell us how you create the dictionary. For dictionaries that are
created using some automated mechanism, we have
<https://download.freedict.org/generated/>. I have tried to stress that in the
README of this repo, ut fd-dictionaries is not holding all our dictionaries,
but only hand-crafted ones.

Long story short: you can hand in a PR to freedict/tools for your importer and
then we can upload it to the before mentioned URL.

**Comment by vpvn** [comment]
One more question, @humenda . Can be generated dictionary bigger than 100Mb and use, for example, data from hand-crafted tei file from this repo? And this resulting file can be requested by api? So, hand-crafted part of this dictionary will be in this repo and the generated part, as a script, in the tools.

**Comment by humenda** [comment]
There's no size constraint for generated dictionaries. However, I'm afraid
that a dictionary can exist only as either hand-written or generated. However, this
is not a problem because if you submit the code for the generator to us, we
can import the dictionary and remove the old eng-rus -- it has less than 2,000
headwords. Your dictionary is certainly superior.
