### ISSUE TITLE
How to indicate examples inside sense

### ISSUE THREAD

**Issue by ilius** [freedict/fd-dictionaries#60]
I'd like to know what's the standard (or the best) way to indicate examples of a term, inside a sense.

Here is what I'm doing currently:

	<sense n="1" xml:lang="fa">
		<gramGrp>
			<pos norm="adjective">صفت</pos>
		</gramGrp>
		<sense xml:lang="fa">
			<def>
				definition...
				<p class="example">
					<div xml:lang="en">example 1 ...</div>
					<div xml:lang="fa">tranlation of example 1 ...</div>
					<div xml:lang="en">example 2 ...</div>
					<div xml:lang="fa">tranlation of example 2 ...</div>
				</p>
			</def>
		</sense>
	</sense>

Or maybe I should use `<p type="example">` instead of `<p class="example">`

I'd also consider this:

	<sense n="1" xml:lang="fa">
		<gramGrp>
			<pos norm="adjective">صفت</pos>
		</gramGrp>
		<sense xml:lang="fa">
			<def>
				definition...
				<br/>
				<spanGrp type="example">
					<span xml:lang="en">example 1 ...</span>
					<br/>
					<span xml:lang="fa">tranlation of example 1 ...</span>
				</spanGrp>
				<br/>
				<spanGrp type="example">
					<span xml:lang="en">example 2 ...</span>
					<br/>
					<span xml:lang="fa">tranlation of example 2 ...</span>
				</spanGrp>
			</def>
		</sense>
	</sense>

I suppose `<span>` is like HTML and does not add newlines, that's why I added these `<br/>`

The reason `xml:lang=` attributes are specificed is to change the direction of text, and possibly style (text color, font etc) when rendering to HTML.

I looked at more than 20 existing FreeDict dictionaries and didn't find anything like this.

Thanks in advance

**Comment by respiranto** [comment]
Hi Saeed,
On 27/12/2020 22:01, Saeed Rasooli wrote:
> I'd like to know what's the standard (or the best) way to indicate examples of a term, within a sense.

I had a similar question some time ago.  As an answer to that question,
there is a list of some options in the Wiki [0:25.3].  I suggest
following a.1) or a.2) under Answers/examples/options.

Generally, you should use <cit type="example" />, right within <sense
/>.  No need for nested sense elements.

> I suppose `<span>` is like HTML and does not add newlines, that's why I added these `<br/>`
>
> The reason `xml:lang=` attributes are specificed is to change the direction of text, and possibly style (text color, font etc) when rendering to HTML.

Presentational aspects such as line breaks or color should not be
represented in (FreeDict) TEI.  If the HTML output does not look good,
the HTML generator should be improved.

> I looked at more than 20 existing FreeDict dictionaries and didn't find anything like this.

`grep' can sometimes be helpful.


By the way, I do not see no actual translations of the headwords.  Do I
assume correctly that you simply omitted them?


Regards,
Einhard


[0] https://github.com/freedict/fd-dictionaries/wiki/discussion-TEI

**Comment by ilius** [comment]
Thanks for your response.
I will go with **a.2**

> By the way, I do not see no actual translations of the headwords.  Do I assume correctly that you simply omitted them?

No, the translation was `definition...` inside `<def>`

But I'm switching from `<def>` to `<cit>`

One reason I chose `<def>` over `<cit>` was that in the existing glossaries like `eng-deu.tei`, `<cit>` tags are all directly under first-level `<sense>` which is under `<entry>`.
Unlike `<def>` which is under second-level `<sense>`.
For example:

    <entry>
      <form>
        <orth>-'s</orth>
        <pron>/s/</pron>
        <pron>/z/</pron>
        <pron>/əz/</pron>
        <pron>/ɪz/</pron>
      </form>
      <gramGrp>
        <pos>particle</pos>
      </gramGrp>
      <sense>
        <cit type="trans" xml:lang="de">
          <quote>-s</quote>
          <quote>der</quote>
          <quote>des</quote>
          <quote>von</quote>
        </cit>
        <sense>
          <def>possessive marker</def>
        </sense>
      </sense>
    </entry>


**So my question**: is it okay to use `<cit>` under second-level `<sense>`?
For example:

			<entry>
				<form xml:lang="en">
					<orth>a</orth>
					<pron>ǝ</pron>
				</form>
				<sense n="1" xml:lang="fa">
					<gramGrp>
						<pos norm="adjective">صفت</pos>
					</gramGrp>
					<sense xml:lang="fa">
						<cit type="trans">
							<quote>translation...</quote>
						</cit>
						<cit type="example">
							<quote xml:lang="en">I see a man</quote>
							<cit type="trans" xml:lang="fa">
								<quote>(translation of: I see a man)</quote>
							</cit>
						</cit>
						<cit type="example">
							<quote xml:lang="en">once a day</quote>
							<cit type="trans" xml:lang="fa">
								<quote>(translation of: once a day)</quote>
							</cit>
						</cit>
					</sense>
					<sense xml:lang="fa">
						...
					</sense>
				</sense>
			</entry>

**Comment by respiranto** [comment]
> But I'm switching from `<def>` to `<cit>`
> 
> One reason I chose `<def>` over `<cit>` was that in the existing glossaries like `eng-deu.tei`, `<cit>` tags are all directly under first-level `<sense>` which is under `<entry>`.

Both def and cit elements may be placed inside any sense element (though
it should usually be the lowest sense element in the hierarchy, in the
case of nested senses.

def elements should, as far as I know, not be used for translations, but
only for definitions.  There appear to be some dictionaries that do though.

For translations, <cit type=trans /> should be used instead, see also [0].

> **So my question**: is it okay to use `<cit>` under second-level `<sense>`?

If nested sense elements are valid, which I believe they are (you quoted
from an exiting dictionary above, right?), so are cit elements within these.


[0]
https://github.com/freedict/fd-dictionaries/wiki/FreeDict-HOWTO-%E2%80%93-Writing-Text-Encoding-Initiative-XML-Files

**Comment by ilius** [comment]
Thanks.
That clears it up.
I will update my tei file and PyGlossary accordingly.

**Comment by ilius** [comment]
Do you think I should add my Persian <-> English glossary here?
It's about 85 MB, which is bigger than Github's max recommended size, 50 MB.
Although there are 2 other big files here as well:
93M	jpn-eng/jpn-eng.tei
72M	jpn-deu/jpn-deu.tei

**Comment by humenda** [comment]
It would be good to discuss questions unrelated to this issue on the mailing
list: <https://www.freelists.org/list/freedict>.
But here it goes anyway:

>Do you think I should add my Persian <-> English glossary here?
>It's about 85 MB, which is bigger than Github's max recommended size, 50 MB.
>Although there are 2 other big files here as well:
>93M	jpn-eng/jpn-eng.tei
>72M	jpn-deu/jpn-deu.tei

These two are left overs and nobody took the time yet to clean them up, so
don't serve as an example.

The answer to your question largely depends on your sources. If that
dictionary is generated from a different source, so that TEI is only the
resulting format, we storegenerated, AKA auto-imported dictionaries not in a
Git repository, but put the importer programs in
[tools](https://github.com/freedict/tools) and import + release the dictionary
regularly. Generated dictionaries are stored both as a release and the latest
version at <https://download.freedict.org/generated>. This is also explained
in the readme of this repository, at our downloads page and to some extend in
the HOWTO.

If you wrote the dictionary by hand in TEI an it is larger than 50mb, we have
to find a different solution.
